<?php
//// ==================================================================
// Theme options settings
//// ==================================================================
$themename  = 'Theme';
$shortname  = 'ace_';
$options    = array (

array(
  'name'  =>  'Theme',
  'type'  =>  'header'
),

//// ==================================================================
// General
//// ==================================================================
array('type'=>'class','class'=>'<div id="general">'),
array(
  'name'  =>  'Custom favicon',
  'id'    =>  $shortname.'favicon',
  'type'  =>  'upload',
  "size"  =>  '16x16',
  'note'  =>  '',
  'std'   =>  '',
),
array(
  'name'  =>  'Footer credit',
  'id'    =>  $shortname.'footer_credit',
  'type'  =>  'textarea',
  'note'  =>  '',
),
array('type'=>'class','class'=>'</div>'),

//// ==================================================================
// Colors
//// ==================================================================
array('type'=>'class','class'=>'<div id="colors">'),
// ============================== Overall
array(
  'type'  => 'title',
  'note'  => 'Overall',
),
array(
  'name'  => 'Text color',
  'id'    => $shortname.'text_color',
  'type'  => 'color',
  'note'  => 'text_color',
  'std'   => '#555555',
),
// ============================== Menu
array(
  'type'  => 'title',
  'note'  => 'Menu',
),
array(
  'name'  => 'Navigation menu background color',
  'id'    => $shortname.'nav_bg',
  'type'  => 'color',
  'note'  => 'nav_bg',
  'std'   => '#000000',
),
array(
  'name'  => 'Color',
  'id'    => $shortname.'nav_link',
  'type'  => 'color',
  'note'  => 'nav_link',
  'std'   => '#ffffff',
),
array(
  'name'  => 'Hover color',
  'id'    => $shortname.'nav_link_hover',
  'type'  => 'color',
  'note'  => 'nav_link_hover',
  'std'   => '#ffffff',
),
// ============================== Slider
array(
  'type'  => 'title',
  'note'  => 'Slider',
),
array(
  'name'  => 'Arrow background color',
  'id'    => $shortname.'arrow_bg',
  'type'  => 'color',
  'note'  => 'arrow_bg',
  'std'   => '#ffffff',
),
array(
  'name'  => 'Caption text border color',
  'id'    => $shortname.'caption_text_border',
  'type'  => 'color',
  'note'  => 'caption_text_border',
  'std'   => '#c2a34f',
),
array(
  'name'  => 'Caption background color',
  'id'    => $shortname.'caption_bg',
  'type'  => 'color',
  'note'  => 'caption_bg',
  'std'   => '#f9f9f9',
),
// ============================== Page/Post Title
array(
  'type'  => 'title',
  'note'  => 'Page/Post Title',
),
array(
  'name'  => 'Page title color',
  'id'    => $shortname.'page_post_title',
  'type'  => 'color',
  'note'  => 'page_post_title',
  'std'   => '#000000',
),
array(
  'name'  => 'Post title link color',
  'id'    => $shortname.'page_post_title_link',
  'type'  => 'color',
  'note'  => 'page_post_title_link',
  'std'   => '#000000',
),
array(
  'name'  => 'Post title link hover color',
  'id'    => $shortname.'page_post_title_link_hover',
  'type'  => 'color',
  'note'  => 'page_post_title_link_hover',
  'std'   => '#000000',
),
array(
  'name'  => 'Page/Post title border color',
  'id'    => $shortname.'page_post_title_border',
  'type'  => 'color',
  'note'  => 'page_post_title_border',
  'std'   => '#000000',
),
array(
  'name'  => 'Page/Post meta (categories, comment etc) border color',
  'id'    => $shortname.'page_post_meta_border',
  'type'  => 'color',
  'note'  => 'page_post_meta_border',
  'std'   => '#000000',
),
array(
  'name'  => 'Related posts wrapper border color',
  'id'    => $shortname.'related_border',
  'type'  => 'color',
  'note'  => 'related_border',
  'std'   => '#c2a34f',
),
array(
  'name'  => 'Related title background color',
  'id'    => $shortname.'related_bg_color',
  'type'  => 'color',
  'note'  => 'related_bg_color',
  'std'   => '#c2a34f',
),
array(
  'name'  => 'Related title text color',
  'id'    => $shortname.'related_text_color',
  'type'  => 'color',
  'note'  => 'related_text_color',
  'std'   => '#ffffff',
),
// ============================== Sidebar
array(
  'type'  => 'title',
  'note'  => 'Sidebar',
),
array(
  'name'  => 'Sidebar widget title color',
  'id'    => $shortname.'sidebar_title',
  'type'  => 'color',
  'note'  => 'sidebar_title',
  'std'   => '#000000',
),
array(
  'name'  => 'Sidebar widget title border color',
  'id'    => $shortname.'sidebar_title_border',
  'type'  => 'color',
  'note'  => 'sidebar_title_border',
  'std'   => '#000000',
),
// ============================== Footer
array(
  'type'  => 'title',
  'note'  => 'Footer',
),
array(
  'name'  => 'Footer widget title color',
  'id'    => $shortname.'footer_title',
  'type'  => 'color',
  'note'  => 'footer_title',
  'std'   => '#000000',
),
array(
  'name'  => 'Footer border color',
  'id'    => $shortname.'footer_border',
  'type'  => 'color',
  'note'  => 'footer_border',
  'std'   => '#000000',
),
array(
  'name'  => 'Footer credit border color',
  'id'    => $shortname.'footer_credit_border',
  'type'  => 'color',
  'note'  => 'footer_credit_border',
  'std'   => '#c2a34f',
),
// ============================== Links
array(
  'type'  => 'title',
  'note'  => 'Links',
),
array(
  'name'  => 'Color',
  'id'    => $shortname.'link',
  'type'  => 'color',
  'note'  => 'link',
  'std'   => '#c2a34f',
),
array(
  'name'  => 'Hover color',
  'id'    => $shortname.'link_hover',
  'type'  => 'color',
  'note'  => 'link_hover',
  'std'   => '#000000',
),
// ============================== Heading
array(
  'type'  => 'title',
  'note'  => 'Heading',
),
array(
  'name'  => 'H1 Color',
  'id'    => $shortname.'h1',
  'type'  => 'color',
  'note'  => 'h1',
  'std'   => '#000000',
),
array(
  'name'  => 'H2 Color',
  'id'    => $shortname.'h2',
  'type'  => 'color',
  'note'  => 'h2',
  'std'   => '#000000',
),
array(
  'name'  => 'H3 Color',
  'id'    => $shortname.'h3',
  'type'  => 'color',
  'note'  => 'h3',
  'std'   => '#333333',
),
array(
  'name'  => 'H4 Color',
  'id'    => $shortname.'h4',
  'type'  => 'color',
  'note'  => 'h4',
  'std'   => '#333333',
),
array(
  'name'  => 'H5 Color',
  'id'    => $shortname.'h5',
  'type'  => 'color',
  'note'  => 'h5',
  'std'   => '#555555',
),
array(
  'name'  => 'H6 Color',
  'id'    => $shortname.'h6',
  'type'  => 'color',
  'note'  => 'h6',
  'std'   => '#555555',
),
// ============================== Button
array(
  'type'  => 'title',
  'note'  => 'Button',
),
array(
  'name'  => 'Background color',
  'id'    => $shortname.'button_bg',
  'type'  => 'color',
  'note'  => 'button_bg',
  'std'   => '#c2a34f',
),
array(
  'name'  => 'Border color',
  'id'    => $shortname.'button_border',
  'type'  => 'color',
  'note'  => 'button_border',
  'std'   => '#c2a34f',
),
array(
  'name'  => 'Text color',
  'id'    => $shortname.'button_text',
  'type'  => 'color',
  'note'  => 'button_text',
  'std'   => '#ffffff',
),
array(
  'name'  => 'Hover background color',
  'id'    => $shortname.'button_bg_hover',
  'type'  => 'color',
  'note'  => 'button_bg_hover',
  'std'   => '#000000',
),
array(
  'name'  => 'Hover border color',
  'id'    => $shortname.'button_border_hover',
  'type'  => 'color',
  'note'  => 'button_border_hover',
  'std'   => '#000000',
),
array(
  'name'  => 'Hover text color',
  'id'    => $shortname.'button_text_hover',
  'type'  => 'color',
  'note'  => 'button_text_hover',
  'std'   => '#ffffff',
),
// ============================== Accordion
array(
  'type'  => 'title',
  'note'  => 'Accordion',
),
array(
  'name'  => 'Background color',
  'id'    => $shortname.'accordion_bg',
  'type'  => 'color',
  'note'  => 'accordion_bg',
  'std'   => '#c2a34f',
),
array(
  'name'  => 'Text color',
  'id'    => $shortname.'accordion_text',
  'type'  => 'color',
  'note'  => 'accordion_text',
  'std'   => '#ffffff',
),
array(
  'name'  => 'Hover background color',
  'id'    => $shortname.'accordion_bg_hover',
  'type'  => 'color',
  'note'  => 'accordion_bg_hover',
  'std'   => '#000000',
),
array(
  'name'  => 'Hover text color',
  'id'    => $shortname.'accordion_text_hover',
  'type'  => 'color',
  'note'  => 'accordion_text_hover',
  'std'   => '#ffffff',
),
// ============================== Social Media
array(
  'type'  => 'title',
  'note'  => 'Social Media Icons',
),
array(
  'name'  => 'Twitter',
  'id'    => $shortname.'widget_twitter_bg',
  'type'  => 'color',
  'note'  => 'widget_twitter_bg',
  'std'   => '#cccccc',
),
array(
  'name'  => 'Twitter hover',
  'id'    => $shortname.'widget_twitter_bg_hover',
  'type'  => 'color',
  'note'  => 'widget_twitter_bg_hover',
  'std'   => '#269dd5',
),
array(
  'name'  => 'Facebook',
  'id'    => $shortname.'widget_fb_bg',
  'type'  => 'color',
  'note'  => 'widget_fb_bg',
  'std'   => '#cccccc',
),
array(
  'name'  => 'Facebook hover',
  'id'    => $shortname.'widget_fb_bg_hover',
  'type'  => 'color',
  'note'  => 'widget_fb_bg_hover',
  'std'   => '#0c42b2',
),
array(
  'name'  => 'Email',
  'id'    => $shortname.'widget_email_bg',
  'type'  => 'color',
  'note'  => 'widget_email_bg',
  'std'   => '#cccccc',
),
array(
  'name'  => 'Email hover',
  'id'    => $shortname.'widget_email_bg_hover',
  'type'  => 'color',
  'note'  => 'widget_email_bg_hover',
  'std'   => '#aaaaaa',
),
array(
  'name'  => 'RSS Feed',
  'id'    => $shortname.'widget_rss_bg',
  'type'  => 'color',
  'note'  => 'widget_rss_bg',
  'std'   => '#cccccc',
),
array(
  'name'  => 'RSS Feed hover',
  'id'    => $shortname.'widget_rss_bg_hover',
  'type'  => 'color',
  'note'  => 'widget_rss_bg_hover',
  'std'   => '#f49000',
),
array(
  'name'  => 'Google Plus',
  'id'    => $shortname.'widget_google_bg',
  'type'  => 'color',
  'note'  => 'widget_twitter_bg',
  'std'   => '#cccccc',
),
array(
  'name'  => 'Google Plus hover',
  'id'    => $shortname.'widget_google_bg_hover',
  'type'  => 'color',
  'note'  => 'widget_twitter_bg_hover',
  'std'   => '#fd3000',
),
array(
  'name'  => 'Flickr',
  'id'    => $shortname.'widget_flickr_bg',
  'type'  => 'color',
  'note'  => 'widget_flickr_bg',
  'std'   => '#cccccc',
),
array(
  'name'  => 'Flickr hover',
  'id'    => $shortname.'widget_flickr_bg_hover',
  'type'  => 'color',
  'note'  => 'widget_flickr_bg_hover',
  'std'   => '#fc0077',
),
array(
  'name'  => 'Linkedin',
  'id'    => $shortname.'widget_linkedin_bg',
  'type'  => 'color',
  'note'  => 'widget_linkedin_bg',
  'std'   => '#cccccc',
),
array(
  'name'  => 'Linkedin hover',
  'id'    => $shortname.'widget_linkedin_bg_hover',
  'type'  => 'color',
  'note'  => 'widget_linkedin_bg_hover',
  'std'   => '#0d5a7b',
),
array(
  'name'  => 'YouTube',
  'id'    => $shortname.'widget_youtube_bg',
  'type'  => 'color',
  'note'  => 'widget_youtube_bg',
  'std'   => '#cccccc',
),
array(
  'name'  => 'YouTube hover',
  'id'    => $shortname.'widget_youtube_bg_hover',
  'type'  => 'color',
  'note'  => 'widget_youtube_bg_hover',
  'std'   => '#ff0000',
),
array(
  'name'  => 'Vimeo',
  'id'    => $shortname.'widget_vimeo_bg',
  'type'  => 'color',
  'note'  => 'widget_vimeo_bg',
  'std'   => '#cccccc',
),
array(
  'name'  => 'Vimeo hover',
  'id'    => $shortname.'widget_vimeo_bg_hover',
  'type'  => 'color',
  'note'  => 'widget_vimeo_bg_hover',
  'std'   => '#00c1f8',
),
array(
  'name'  => 'Instagram',
  'id'    => $shortname.'widget_instagram_bg',
  'type'  => 'color',
  'note'  => 'widget_instagram_bg',
  'std'   => '#cccccc',
),
array(
  'name'  => 'Instagram hover',
  'id'    => $shortname.'widget_instagram_bg_hover',
  'type'  => 'color',
  'note'  => 'widget_instagram_bg_hover',
  'std'   => '#194f7a',
),
array(
  'name'  => 'BlogLovin',
  'id'    => $shortname.'widget_bloglovin_bg',
  'type'  => 'color',
  'note'  => 'widget_bloglovin_bg',
  'std'   => '#cccccc',
),
array(
  'name'  => 'BlogLovin hover',
  'id'    => $shortname.'widget_bloglovin_bg_hover',
  'type'  => 'color',
  'note'  => 'widget_bloglovin_bg_hover',
  'std'   => '#00c4fd',
),
array(
  'name'  => 'Pinterest',
  'id'    => $shortname.'widget_pinterest_bg',
  'type'  => 'color',
  'note'  => 'widget_twitter_bg',
  'std'   => '#cccccc',
),
array(
  'name'  => 'Pinterest hover',
  'id'    => $shortname.'widget_pinterest_bg_hover',
  'type'  => 'color',
  'note'  => 'widget_twitter_bg_hover',
  'std'   => '#c70505',
),
array(
  'name'  => 'Tumblr',
  'id'    => $shortname.'widget_tumblr_bg',
  'type'  => 'color',
  'note'  => 'widget_tumblr_bg',
  'std'   => '#cccccc',
),
array(
  'name'  => 'Tumblr hover',
  'id'    => $shortname.'widget_tumblr_bg_hover',
  'type'  => 'color',
  'note'  => 'widget_tumblr_bg_hover',
  'std'   => '#304d6b',
),
array('type'=>'class','class'=>'</div>'),

//// ==================================================================
// Extra inputs
//// ==================================================================
array('type'=>'class','class'=>'<div id="extra">'),
array(
  'name'  => 'Header script(s)',
  'id'    => $shortname.'header_scripts',
  'type'  => 'textarea',
  'note'  => 'Place your necessary code here, anything that needs to be placed before <strong>&#60;/head&#62;</strong>.',
),
array(
  'name'  => 'Footer script(s)',
  'id'    => $shortname.'footer_scripts',
  'type'  => 'textarea',
  'note'  => 'Place your necessary code here, anything that needs to be placed before <strong>&#60;/body&#62;</strong>.',
),
array(
  'name'  => 'Custom CSS',
  'id'    => $shortname.'css',
  'type'  => 'textarea',
  'note'  => 'Add some custom CSS to your theme.',
),
array('type'=>'class','class'=>'</div>'),

//// ==================================================================
// Slider
//// ==================================================================
array('type'=>'class','class'=>'<div id="slider">'),
array(
  'name'  => 'Enable slider',
  'id'    => $shortname.'feature_enable',
  'type'  => 'checkbox',
  'note'  => '<strong>Enable</strong> slider.',
),
array(
  'name'  => 'Show Title &amp; Content',
  'id'    => $shortname.'feature_title_enable',
  'type'  => 'checkbox',
  'note'  => 'Show <strong>posts title &amp; content</strong> on slider',
),
array(
  'name'    => 'Sliding style',
  'id'      => $shortname.'featured_slide_style',
  'type'    => 'select',
  'std'     => 'random',
  'options' => array( 'random', 'sliceDown', 'sliceDownLeft', 'sliceUp', 'sliceUpLeft', 'sliceUpDown', 'sliceUpDownLeft', 'fold', 'fade', 'slideInRight', 'slideInLeft', 'boxRandom', 'boxRain', 'boxRainReverse', 'boxRainGrow', 'boxRainGrowReverse' ),
  'note'    => 'How NivoSlider should slide the image.',
),
array(
  'name'    => 'Pause',
  'id'      => $shortname.'featured_slide_pause',
  'type'    => 'select',
  'std'     => '3000',
  'options' => array( '1000', '2000', '3000', '4000', '5000' ),
  'note'    => 'Time pause on each slide. 1000 = 1 second.',
),
array(
  'name'    => 'Speed',
  'id'      => $shortname.'featured_slide_speed',
  'type'    => 'select',
  'std'     => '300',
  'options' => array( '100', '200', '300', '400', '500', '1000', ),
  'note'    => 'Speed of transition. 1000 = 1 second.',
),
array('type'=>'class','class'=>'</div>'),

//// ==================================================================
// Social media
//// ==================================================================
array('type'=>'class','class'=>'<div id="socials">'),
array(
  'name'  => 'Enable header social media icons',
  'id'    => $shortname.'socials_enabled',
  'type'  => 'checkbox',
  'note'  => 'Enable <strong>Social Media icons</strong> on top of the header.',
),
array(
  'name'  => 'Twitter',
  'id'    => $shortname.'twitter',
  'type'  => 'text',
  'note'  => 'Twitter profile page URL',
),
array(
  'name'  => 'Twitter icon color',
  'id'    => $shortname.'twitter_bg',
  'type'  => 'color',
  'note'  => 'twitter_bg',
  'std'   => '#000000',
),
array(
  'name'  => 'Twitter icon color (Hover)',
  'id'    => $shortname.'twitter_bg_hover',
  'type'  => 'color',
  'note'  => 'twitter_bg_hover',
  'std'   => '#c2a34f',
),
array(
  'name'  => 'Facebook',
  'id'    => $shortname.'facebook',
  'type'  => 'text',
  'note'  => 'Facebook profile page URL',
),
array(
  'name'  => 'Facebook icon color',
  'id'    => $shortname.'facebook_bg',
  'type'  => 'color',
  'note'  => 'facebook_bg',
  'std'   => '#000000',
),
array(
  'name'  => 'Facebook icon color (Hover)',
  'id'    => $shortname.'facebook_bg_hover',
  'type'  => 'color',
  'note'  => 'facebook_bg_hover',
  'std'   => '#c2a34f',
),
array(
  'name'  => 'Pinterest',
  'id'    => $shortname.'pinterest',
  'type'  => 'text',
  'note'  => 'Pinterest profile page URL',
),
array(
  'name'  => 'Pinterest icon color',
  'id'    => $shortname.'pinterest_bg',
  'type'  => 'color',
  'note'  => 'pinterest_bg',
  'std'   => '#000000',
),
array(
  'name'  => 'Pinterest icon color (Hover)',
  'id'    => $shortname.'pinterest_bg_hover',
  'type'  => 'color',
  'note'  => 'pinterest_bg_hover',
  'std'   => '#c2a34f',
),
array(
  'name'  => 'Instagram',
  'id'    => $shortname.'instagram',
  'type'  => 'text',
  'note'  => 'Instagram profile page URL',
),
array(
  'name'  => 'Instagram icon color',
  'id'    => $shortname.'instagram_bg',
  'type'  => 'color',
  'note'  => 'instagram_bg',
  'std'   => '#000000',
),
array(
  'name'  => 'Instagram icon color (Hover)',
  'id'    => $shortname.'instagram_bg_hover',
  'type'  => 'color',
  'note'  => 'instagram_bg_hover',
  'std'   => '#c2a34f',
),
array(
  'name'  => 'LinkedIn',
  'id'    => $shortname.'linkedin',
  'type'  => 'text',
  'note'  => 'LinkedIn profile page URL',
),
array(
  'name'  => 'LinkedIn icon color',
  'id'    => $shortname.'linkedin_bg',
  'type'  => 'color',
  'note'  => 'linkedin_bg',
  'std'   => '#000000',
),
array(
  'name'  => 'LinkedIn icon color (Hover)',
  'id'    => $shortname.'linkedin_bg_hover',
  'type'  => 'color',
  'note'  => 'linkedin_bg_hover',
  'std'   => '#c2a34f',
),
array(
  'name'  => 'YouTube',
  'id'    => $shortname.'youtube',
  'type'  => 'text',
  'note'  => 'YouTube profile page URL',
),
array(
  'name'  => 'YouTube icon color',
  'id'    => $shortname.'youtube_bg',
  'type'  => 'color',
  'note'  => 'youtube_bg',
  'std'   => '#000000',
),
array(
  'name'  => 'YouTube icon color (Hover)',
  'id'    => $shortname.'youtube_bg_hover',
  'type'  => 'color',
  'note'  => 'youtube_bg_hover',
  'std'   => '#c2a34f',
),
array(
  'name'  => 'Vimeo',
  'id'    => $shortname.'vimeo',
  'type'  => 'text',
  'note'  => 'Vimeo profile page URL',
),
array(
  'name'  => 'Vimeo icon color',
  'id'    => $shortname.'vimeo_bg',
  'type'  => 'color',
  'note'  => 'vimeo_bg',
  'std'   => '#000000',
),
array(
  'name'  => 'Vimeo icon color (Hover)',
  'id'    => $shortname.'vimeo_bg_hover',
  'type'  => 'color',
  'note'  => 'vimeo_bg_hover',
  'std'   => '#c2a34f',
),
array(
  'name'  => 'Google Plus',
  'id'    => $shortname.'google_plus',
  'type'  => 'text',
  'note'  => 'Google Plus profile page URL',
),
array(
  'name'  => 'Google Plus icon color',
  'id'    => $shortname.'google_plus_bg',
  'type'  => 'color',
  'note'  => 'google_plus_bg',
  'std'   => '#000000',
),
array(
  'name'  => 'Google Plus icon color (Hover)',
  'id'    => $shortname.'google_plus_bg_hover',
  'type'  => 'color',
  'note'  => 'google_plus_bg_hover',
  'std'   => '#c2a34f',
),
array(
  'name'  => 'Flickr',
  'id'    => $shortname.'flickr',
  'type'  => 'text',
  'note'  => 'Flickr profile page URL',
),
array(
  'name'  => 'Flickr icon color',
  'id'    => $shortname.'flickr_bg',
  'type'  => 'color',
  'note'  => 'flickr_bg',
  'std'   => '#000000',
),
array(
  'name'  => 'Flickr icon color (Hover)',
  'id'    => $shortname.'flickr_bg_hover',
  'type'  => 'color',
  'note'  => 'flickr_bg_hover',
  'std'   => '#c2a34f',
),
array(
  'name'  => 'Bloglovin',
  'id'    => $shortname.'bloglovin',
  'type'  => 'text',
  'note'  => 'Bloglovin profile page URL',
),
array(
  'name'  => 'Bloglovin icon color',
  'id'    => $shortname.'bloglovin_bg',
  'type'  => 'color',
  'note'  => 'bloglovin_bg',
  'std'   => '#000000',
),
array(
  'name'  => 'Bloglovin icon color (Hover)',
  'id'    => $shortname.'bloglovin_bg_hover',
  'type'  => 'color',
  'note'  => 'bloglovin_bg_hover',
  'std'   => '#c2a34f',
),
array(
  'name'  => 'Tumblr',
  'id'    => $shortname.'tumblr',
  'type'  => 'text',
  'note'  => 'Tumblr page URL',
),
array(
  'name'  => 'Tumblr icon color',
  'id'    => $shortname.'tumblr_bg',
  'type'  => 'color',
  'note'  => 'tumblr_bg',
  'std'   => '#000000',
),
array(
  'name'  => 'Tumblr icon color (Hover)',
  'id'    => $shortname.'tumblr_bg_hover',
  'type'  => 'color',
  'note'  => 'tumblr_bg_hover',
  'std'   => '#c2a34f',
),
array(
  'name'  => 'RSS feed',
  'id'    => $shortname.'rss',
  'type'  => 'text',
  'note'  => 'rss profile page URL',
),
array(
  'name'  => 'RSS feed icon color',
  'id'    => $shortname.'rss_bg',
  'type'  => 'color',
  'note'  => 'rss_bg',
  'std'   => '#000000',
),
array(
  'name'  => 'RSS feed icon color (Hover)',
  'id'    => $shortname.'rss_bg_hover',
  'type'  => 'color',
  'note'  => 'rss_bg_hover',
  'std'   => '#c2a34f',
),
array(
  'name'  => 'Email',
  'id'    => $shortname.'email',
  'type'  => 'text',
  'note'  => 'Email Address',
),
array(
  'name'  => 'Email icon color',
  'id'    => $shortname.'email_bg',
  'type'  => 'color',
  'note'  => 'email_bg',
  'std'   => '#000000',
),
array(
  'name'  => 'Email icon color (Hover)',
  'id'    => $shortname.'email_bg_hover',
  'type'  => 'color',
  'note'  => 'email_bg_hover',
  'std'   => '#c2a34f',
),
array('type'=>'class','class'=>'</div>'),

//// ==================================================================
// Entry
//// ==================================================================
array('type'=>'class','class'=>'<div id="entry">'),
array(
  'name'  => 'Enable Breadcrumb navigation',
  'id'    => $shortname.'enable_breadcrumb',
  'type'  => 'checkbox',
  'note'  => 'Enable <strong>breadcrumb navigation</strong>',
),
array(
  'name'  => 'Blog author',
  'id'    => $shortname.'blog_author',
  'type'  => 'checkbox',
  'note'  => 'Check to remove <strong>author</strong> on blog post.',
),
array(
  'name'  => 'Blog author biography',
  'id'    => $shortname.'blog_author_bio',
  'type'  => 'checkbox',
  'note'  => 'Check to show <strong>author biography</strong> on blog post.',
),
array(
  'name'  => 'Use excerpt summary',
  'id'    => $shortname.'enable_excerpt',
  'type'  => 'checkbox',
  'note'  => 'Enable <strong>excerpt entry</strong>',
),
array(
  'name'  => 'Enable related post',
  'id'    => $shortname.'enable_related',
  'type'  => 'checkbox',
  'note'  => 'Enable <strong>related posts</strong>. <em>Works by relevant "Post Tag"</em>',
),
array(
  'name'  => 'Enable feature thumbnail',
  'id'    => $shortname.'enable_post_thumbnail',
  'type'  => 'checkbox',
  'note'  => 'Enable <strong>Post Thumbnail</strong>',
),
array(
  'id'    => $shortname.'thumb_width',
  'type'  => 'thumb',
  'std'   => '100',
  'note'  => 'Width',
),
array(
  'id'    => $shortname.'thumb_height',
  'type'  => 'thumb',
  'std'   => '100',
  'note'  => 'Height',
),
array('type'=>'class','class'=>'<div style=\"height: 10px; clear: both;\">&nbsp;</div>'),
array('type'=>'class','class'=>'<hr />'),
array('type'=>'class','class'=>'</div>'),

//// ==================================================================
// 404 Error
//// ==================================================================
array('type'=>'class','class'=>'<div id="404">'),
array(
  'name'  => '404 Page Content',
  'id'    => $shortname.'404_page',
  'type'  => 'editor',
  'note'  => '',
),
array('type'=>'class','class'=>'</div>'),


);